import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  dialect: 'postgresql',
  // better-auth's own tables (src/db/auth-schema.ts) are generated by its CLI
  // (`db:generate:auth`) as a plain Drizzle schema file, then migrated through
  // this SAME drizzle-kit flow — no separate migration step needed.
  schema: ['./src/db/schema.ts', './src/db/auth-schema.ts'],
  out: './drizzle',
  dbCredentials: {
    url: process.env['DATABASE_URL'] ?? 'postgresql://postgres:postgres@localhost:5433/koi',
  },
});
